version: '3'
 
services:
  web1:
   restart: always
   build: .
   ports:
     - "8000:5000"
   command: python3 test1.py
   links:
     - db1
   depends_on:
     - db1

  db1:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_DATABASE: 'ride'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3309:3306"
    expose:
     # Opens port 3306 on the container
     - '3306'
     # Where our data will be persisted
    volumes:
      - my-db1:/var/lib/mysql
# Names our volume
volumes:
  my-db1:


