version: '3'
 
services:
  web:
   restart: always
   build: .
   ports:
     - "8080:5000"
   command: python3 test.py
   links:
     - db
   depends_on:
     - db
 
  db:
    image: mysql:8.0.17
    restart: always
    environment:
      MYSQL_DATABASE: 'ride'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
   
    ports:
      - "3308:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysq



volumes:
  my-db:
